spring:
  application:
    name: GTEL-Internship

server:
  port: 8089
  error:
    include-message: always
    include-binding-errors: always

#Logs
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.client.RestClient: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http.wire: DEBUG
    org.apache.http.headers: DEBUG

logicom:
  api:
    url: https://quickconnect.logicompartners.com
    customer-id: 2073
    consumer-key: CONSUMER_KEY
    consumer-secret: CONSUMER_SECRET
    access-token-key: TOKEN_KEY

woocommerce:
    api:
      url: https://gtelstore.ma
      key: WOO_KEY
      secret: WOO_SECRET
