spring:
  application:
    name: GTEL-Internship

server:
  port: 8089

#Logs
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.jane.gtelinternship.product.infra.client.logicom.TokenProvider: DEBUG

logicom:
  api:
    url: https://quickconnect.logicompartners.com
    customer-id: 2073
    consumer-key: c555JbpeWjar6q25bhfRV1ogIrq5F8
    consumer-secret: mHU87c9Lcf1xPZRhMAInfv6ld5ryX7
    access-token-key: 7mvmOzYYvZ4wyViklNXKGOc4cd0CGM6G

woocommerce:
    api:
      url: secret
      key: 1234
      secret: secret-123
